pipeline {
  agent any
  stages {
    stage('build start') {
      steps {
        slackSend(message: "Build ${env.BUILD_NUMBER} Started", color: 'good', tokenCredentialId: '7b510914-fd7e-4635-ad2a-b40fa07fe316')
      }
    }      
    stage('git pull') {
        steps {
            // Please enter your git repository
            git url: '<Git URL>', branch: 'main'
        }
    }
    stage('k8s deploy'){
        steps {
            kubernetesDeploy(kubeconfigId: 'kubeconfig',
                 configs: '*.yaml')
        }
    }
    
    stage('send diff') {
        steps {
        slackSend(message: """${env.JOB_NAME} #${env.BUILD_NUMBER} End
        """, color: 'good', tokenCredentialId: '7b510914-fd7e-4635-ad2a-b40fa07fe316')             
        }
    }
    
  }
}